[package]
name = "run-qemu-vfio-windows"
version = "0.1.0"
authors = ["Nikola Kocic <nikolakocic@gmail.com>"]
edition = "2018"

[dependencies]
ctrlc = { version = "3.1.1", features = ["termination"] }
